#!/usr/bin/python

class Constant:
    # PVA return value
    PVA_SUCCESS = 0
    PVA_OK = 0
    PVA_NOK = -1
    PVA_ERR_UNKNOW = -2
    PVA_ERR_NULL_PTR = -3
    PVA_ERR_MALLOC = -4
    PVA_ERR_OPEN_FILE = -5
    PVA_ERR_VALUE = -6
    PVA_ERR_READ_BIT = -7
    PVA_ERR_BASE = -1000
    PVA_ERR_LIST_STREAM = PVA_ERR_BASE - 1
    PVA_ERR_INT = PVA_ERR_BASE - 2
    PVA_ERR_VPU_CODEC_INIT = PVA_ERR_BASE - 3
    PVA_ERR_STREAM = PVA_ERR_BASE - 4
    PVA_ERR_FATAL_THREAD = PVA_ERR_BASE - 5
    PVA_ERR_NOMEM = PVA_ERR_BASE - 6
    PVA_ERR_PROTOL = PVA_ERR_BASE - 7
    PVA_FAIL_SPLIT_FRAME = PVA_ERR_BASE - 8
    PVA_ERR_VPUHW = PVA_ERR_BASE - 9
    PVA_EOS_STREAM_REACHED = PVA_ERR_BASE - 11
